language: java
jdk: oraclejdk13
dist: bionic

script:
  - sudo apt-get install junit4
  - cd ci/src
  - javac -cp /usr/share/java/junit4.jar *.java
  - java -cp /usr/share/java/junit4.jar:. org.junit.runner.JUnitCore CalcTest

after_success:
  - bash <(curl -s https://codecov.io/bash)